<?php

/**
 * @file
 * Contains foureign_contact.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *
 * @return string
 */
function inmobiliaria_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the contact module.
    case 'help.page.inmobiliaria_core.contact':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to manage contact form and send mail') . '</p>';
      return $output;
    
    default:
  }
}

/**
 * Implements hook_page_attachments().
 *
 * @param array $page
 */
function inmobiliaria_core_page_attachments(array &$page) {
  $meta_data_iphone = array(
    '#tag' => 'meta',
    '#attributes' => array(
      'name' => 'format-detection',
      'content' => 'telephone=no',
    ),
  );
  $page['#attached']['html_head'][] = [$meta_data_iphone, 'format-detection'];
  
  $globalSettings = \Drupal::config('inmobiliaria_core.settings');
  $test = $globalSettings->get('code');
  if(!empty($globalSettings->get('code')['script_head']) && !is_null($globalSettings->get('code')['script_head'])) {
    $page['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#attributes' => array('type' => 'text/javascript'),
        '#value' => $globalSettings->get('code')['script_head'],
      ],
      'script_head',
    ];
  }
  
}

/**
 * Implements hook_page_bottom().
 *
 * @param array $page_bottom
 */
function inmobiliaria_core_page_bottom(array &$page_bottom) {
  $globalSettings = \Drupal::config('inmobiliaria_core.settings');
  
  if(!empty($globalSettings->get('code')['script_bottom']) && !is_null($globalSettings->get('code')['script_bottom'])) {
    $page_bottom['myBottomScript'] =
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#attributes' => array('type' => 'text/javascript'),
        '#value' => $globalSettings->get('code')['script_bottom'],
      ];
  }
}